### ISSUE TITLE
M5 Competition Communication

### ISSUE THREAD

**Issue by wanpingDou** [yassineAlouini/ml-experiments#3]
hello, friend, in M5, i saw your sharing notebook. well. thumbs-up.
here https://www.kaggle.com/yassinealouini/seq2seq   in comment:
```
When it works (which isn't the case for now ;)), it is around 1.97. 
This isn't a great score for sure and I am investigating what can be improved. 
I am working on replacing OHE with embeddings. 
Stay tuned for updates (hopefully).
```
I'd like to know if you followed up with this method of optimization and what the results were.
my email is 1601798839@qq.com
expecting your reply ^_^

**Comment by yassineAlouini** [comment]
Hello @wanpingDou. Unfortunately, I was unable to add the embedding layer and I won't have time to do it :(
If things change, I will let you know.
